### ISSUE TITLE
Versioning workflows

### ISSUE THREAD

**Issue by alecandido** [qiboteam/workflows#12]
For the time being we just introduced them, so it was not a major concern, but now we start seeing syncing issues between workflows and repos using them.

Problem is that we are still developing them, so it is quite normal that during development you iterate faster, but we should make such that callers never use development versions, but instead "named" ones, such we do not need to update them constantly.

Following the example of [`actions/checkout`](https://github.com/actions/checkout/tags) and similar actions, we will offer two "lines":
- the **tags**, fully qualified, e.g. `v3.0.2`, according to semver
- the **branches**, e.g. `v3`, following a family of major releases
  - `actions/checkout` uses tags also for these, updating them every time something is published. To me, this partially misses the purpose of tags, since you'd like to consider them fixed points in Git history

So, if you want to have an immutable object, just use the fully qualified tag in your workflow, like `my-favorite-reusable-workflow@v3.0.2`.
If instead you'd like to receive non-breaking updates, use the less qualified branch `v3`.

Unqualified branches like `main` will be dropped or reserved to development, and they should not be used by callers.
In particular, we won't have a branch named `main` (nor `master`, nor `trunk`) and just use as default branch the latest `vX` branch.

Let's start from `v0`, to try a bit the model. We will accept breaking changes in `v0` for a transition period, after that we will move to `v1` and the first breaking change will directly bump to `v2`.

**Comment by alecandido** [comment]
`v1` is currently a mirror of `main`, I will replace in all the repos and then ask @scarrazza to make `v1` the default branch.

`v2` is work-in-progress, and I will soon start the migration of (at least) some workflows.

**Comment by scarrazza** [comment]
Ok, please let me know when `v1` is ready.

**Comment by alecandido** [comment]
> Ok, please let me know when `v1` is ready.

Concerning `v1` itself, even immediately. But no one is pointing there.
I will let you know, when I'll complete the update!

**Comment by alecandido** [comment]
Almost all main repos have now migrated to `v1` (just waiting for Qibolab), and I switched default branch.

This issue can be considered completed (finally).
