### ISSUE TITLE
pip extra 

### ISSUE THREAD

**Issue by Edoardo-Pedicillo** [qiboteam/workflows#24]
This issue is linked to #23. 
As @AleCandido suggested, we could remove the occurrence of ` inputs.environment`and replace it with a dedicated pip extra in the original packages, called `ci`, and then replace these lines:

https://github.com/qiboteam/workflows/blob/d07fa1dce5e7769294760329dc5c90bac396629a/.github/workflows/rules.yml#L44-L51
by 
```suggestion
        pip install .[${{inputs.pip-extras}}]
        pip install .[ci]
```

**Comment by alecandido** [comment]
This is not present any longer.
