### ISSUE TITLE
Drop non-poetry workflows

### ISSUE THREAD

**Issue by alecandido** [qiboteam/workflows#41]
After https://github.com/qiboteam/qibo/pull/816 only Qibolab will be left without Poetry.

We should review the other minor projects, and check if there is anyone still using the pip workflows, and possibly migrate also that.

Otherwise, I would rather support only a single set of tools for Python packaging, and if there are specific needs local workflows are always available (if there will be a massive need to support `setuptools` again, we will reconsider - but only if and when it will happen).

**Comment by andrea-pasquale** [comment]
@AleCandido let me mention that we also have qibojit which is not using poetry.
Before dropping the non-poetry workflows we will need to also port poetry to qibojit.

**Comment by AleCandido** [comment]
Thanks, my bad: I always count the "major" projects as Qibo, Qibolab, and Qibocal. But you're right that also Qibojit is part of the set.

**Comment by AleCandido** [comment]
Now that Qibojit is also using Poetry, do we have any other project still using the non-Poetry workflows?

@andrea-pasquale @Edoardo-Pedicillo @scarrazza

**Comment by scarrazza** [comment]
No, that's it, thanks.

**Comment by alecandido** [comment]
Done in #58, already replaced in `v2`
