### ISSUE TITLE
Add Codecov tokens everywhere

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/workflows#44]
To face the issue of failing uploads (e.g. https://github.com/qiboteam/qibolab/pull/276#issuecomment-1465976946) Codecov now suggests to always use a Codecov token also for public repos.
https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

Our workflows should be already using them, when available:
https://github.com/qiboteam/workflows/blob/4f1b0c0a8dc02df3009d85db509df691155db3fe/.github/workflows/rules-poetry.yml#L81
https://github.com/qiboteam/workflows/blob/4f1b0c0a8dc02df3009d85db509df691155db3fe/.github/workflows/rules.yml#L76

So we should only confirm that we have token set in all repos, to limit upload failures as much as possible.

**Comment by scarrazza** [comment]
I think that's indeed the case.

**Comment by AleCandido** [comment]
> I think that's indeed the case.

I can't see them, so if you confirm that's the case, feel free to close this issue :)

**Comment by andrea-pasquale** [comment]
In Qibocal we have it.
