### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by alecandido** [qiboteam/workflows#7]
At the moment, there is a fake page for this repo:
https://qibogang.github.io/workflows/
but it is not a bad idea to have an actual one.

We could bootstrap an extremely simple page with Next.js as well. In general, we want to:
- document/describe everything we do
- have a consistent stack (we don't want to learn new tools every time we a new iteration of a common problem)
 
One alternative is Sphinx, but there is no Python code, and writing ReStructuredText is more of a pain than Markdown.
The other option, and this is an actual one, is to use the native Jekyll running on GitHub, i.e.
- just make a folder `docs` top-level with md files
- deploy that folder, even without any workflow

Then my actual proposal for this would be:
- [x] make just md files documentation, to describe and document each workflow, and deploy with basic GitHub tools, no workflow needed
  - @Edoardo-Pedicillo in charge to document the goal and usage of the workflows (especially those written by him)
  -  we'll give feedback whenever we'll use; in particular @MatteoRobbiati should migrate his workflow on `qibogang.github.io` to use the one stored here (whenever will be released on `main`)
- [ ] later on, we will define a Next.js layout (further repo) for this simple docs, and possibly only use in the workflow (so not even in Git), such that we can customize this md docs layout but people using it won't have to take care of Next or JS at all (just writing the md files)
  - not urgent, I will later split to a separate issue to the new layout repo
  - it will provide a uniform layout (different from GitHub standard one, closer to Qibo design) for notes on different repos, without any further overhead wrt to writing md
  - we will version the layout with tags, so the workflow downloading it will use the corresponding tag as a parameter, such that the various repo using the layout won't get unexpected upgrade, but they will have to do it explicitly (but just one parameter, the version, for the full layout)
  - since we need some Next expertise, either it will be done by @MatteoRobbiati or by me

**Comment by MatteoRobbiati** [comment]
1. will this `workflows` webpage be used by us for keeping track of the development?
2. what do you mean by "my workflow"? 
3. not related to this, but can I go ahead and fork `qibolab` and `qibocal` so that I can change the theme of `sphinx` for them as well? Doesn't this conflict with the PR I have already opened in the official repos? Maybe there is a possibility to merge those PRs only in our fork?

Sorry for the many questions.

**Comment by AleCandido** [comment]
> will this `workflows` webpage be used by us for keeping track of the development?

No, to describe goal and usage, as it is written above. If you provide a piece of code, you should document it, even briefly. Workflows are code as much as Python is.

> what do you mean by "my workflow"?

The only workflow on the `qibogang.github.io`, that is publishing the website you are writing

**Comment by Edoardo-Pedicillo** [comment]
>  deploy that folder, even without any workflow

@AleCandido, what do you mean?
I have opened the PR #10 in order to fix this issue.

**Comment by AleCandido** [comment]
Since it is actually set, I guess you found out:
![image](https://user-images.githubusercontent.com/10830876/202505985-07b07ff1-0cf4-4997-b761-c06577720823.png)

Whenever #10 will be merged, we should make sure that the branch is automatically modified to `main`, or switch manually ourselves.

**Comment by AleCandido** [comment]
As you can see from the screenshot, you can also play with [Jekyll themes](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll).

But I recommend not to do it: when we'll want to customize the theme, we'll move to Next, instead of Jekyll.

**Comment by alecandido** [comment]
Next.js is on hold, since we're now using a vanilla HTML page. Then there is nothing else to be done for this issue
